# Generated by Django 4.2.5 on 2023-10-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_task_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('ttask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.task')),
            ],
        ),
    ]
