# Generated by Django 4.2.5 on 2023-10-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='history',
            new_name='hist',
        ),
    ]
